#!/usr/bin/python
#
#   Aug/2008: Javier Fuchs                                    |\_/|   
#             Phone (+54 2944) 525173                        /     \  
#             http://southfox.servehttp.com                 /_.~ ~,_\ 
#                                                              \@/    
import cgi;
import os;
import sys;
import time;
import cgitb; cgitb.enable();

import libconfig;

def main():
    libconfig.starthtmlhead();
    libconfig.pagecss();
    print '<META name="DESCRIPTION" content="Javier Fuchs: Biographical Information">';
    print '';
    print '<TITLE>Javier Fuchs: Biographical Information</TITLE>';
    print '';
    print '<STYLE type="text/css">';
    print 'span.c3 {font-size: 80%}';
    print 'span.c2 {font-size: 70%}';
    print 'div.c1 {text-align: center}';
    print '</STYLE>';
    print '</HEAD>';
    print '';
    print '<BODY>';
    print '';
    print '<DIV class="c1">';
    print '<H1>Info... </H1>';
    print '</DIV>';
    print '<HR>';
    print '<H3>Work</H3>';
    print '';
    print '<P><B>2008: <a target="_blank" href="http://www.invap.com.ar/">INVAP SE</a></B><BR>';
    print '<P><B>2007: Living in Bariloche</B><BR>';
    print 'Working from home first by <A target="_blank" href="http://www.spamexperts.com/">SpamExperts</A>, and then for a local software company in Bariloche: <A target="_blank" href="http://www.showposition.com/">Nusoft / Showposition</A>, development of integrated transport software solutions. <BR> </P>';
    print '<P><B>2006-2007: working for Verizon </B><BR>';
    print 'Migrations and maintenance of pre-existing software.  <BR> </P>';
    print '<P><B>2004-2005: working for California Software</B><BR>';
    print 'Working from home by <A target="_blank" href="http://www.calsw.com/">California Software</A>, with AS/400, Unix and Linux, maintenance of software (compilers, servers, scripts) that replicates the';
    print 'AS/400 environment under Unix/Linux. And administration of Unix (AIX) and Linux (Fedora). Configuration and administration of a develoment environment (CVS).<BR></P>';
    print '';
    print '<P><B>2003: in a "telco": <A target="_blank" href="http://www.tecosoft.com.ar/">TecoSoft</A></B><BR>';
    print 'Software related to telecommunications (Phone Tickets and traffic recovery/collection and valorization), migration from to HP Unix 11.11 (from 32 bits to 64';
    print 'bits).<BR>';
    print 'The client: <A target="_blank" href="http://www.telecom.com.ar/">Telecom</A>.<BR>';
    print 'Languages are C/C++, PRO*C, SQL, python and UNIX Shell Script.<BR>';
    print 'Using makeconf and libtool. Analysis, related to high-availability, audit services and low balancing.<BR></P>';
    print '';
    print '<P><B>2000 to 2003: Java </B><BR>';
    print '<A target="_blank" href="http://www.movi.com.ar/">Bell South - Movicom</A><BR>';
    print 'C, C++, Java (J2EE: EJB, JDBC, Swing), PL/SQL, and a lot of unix shell scripts.<BR>';
    print 'Tools: V.Studio, JBuilder 4-5-7, Eclipse, Toad.<BR>';
    print 'Tru64, VMS, Linux (Suse, RH 8) and Solaris 2.7.<BR>';
    print 'Installing and managing JBoss and Weblogic.<BR>';
    print 'Shared librarys for communication with Switch Alkatel EMX 22, Apps. Servers.<BR></P>';
    print '';
    print '<P><B>2000: Low level Software</B><BR>';
    print '<A target="_blank" href="http://www.intersoft.com.ar/">Intersoft S.A.</A><BR>';
    print 'C/C++, Linux, Unix. Database: Essentia and IdeaFix.</P>';
    print '';
    print '<P><B>1998 to 1999: Working by Menem</B><BR>';
    print '<A target="_blank" href="http://www.iadb.org/">DIB (DEVELOPMENT INTERAMERICAN BANK)</A><BR>';
    print 'BID hires me for working in <A target="_blank" href="http://www.mecon.gov.ar/">MINISTRY OF ECONOMY AND PUBLIC WORKS AND SERVICES, SECRETARY OF THE TREASURY</A>.<BR>';
    print 'Reengineering of Central SIDIF (the financial system, budget, etc, of the entire country).<BR>';
    print 'Forms 3.0 Y2K migration. <BR>';
    print 'PRO*C/C++, PL/SQL, shell scripts, Oracle Forms, Report, Menu, Developer 2000 under WNT.<BR>';
    print 'Oracle 7.3<BR> Unix: Unisys, HP.<BR>';
    print '<A href="img/memoBid.jpg">See Letter</A></P>';
    print '';
    print '<P><B>1997 to 1998: C++</B><BR>';
    print '<A target="_blank" href="http://www.casesyst.com.ar/">CASE SYSTEMS S.A.</A><BR>';
    print 'C, C++, Visual C, PRO*C, PL/SQL, shell scripts.<BR>';
    print 'Oracle 7.2, 7.3 <BR>Aix.<BR>';
    print 'Clients :</P>';
    print '';
    print '<UL>';
    print '<LI><A target="_blank" href="http://www.ieci.es">Inform&#225;tica El Corte Ingl&#233;s S.A. (I.E.C.I.S.A.)</A> , Spain</LI>';
    print '';
    print '<LI><A target="_blank" href="http://www.elpalaciodehierro.com.mx/">El Palacio de Hierro Mall</A>, Mexico D.F., Mexico.</LI>';
    print '';
    print '<LI>TIA S.A. Supermarket, Buenos Aires, Corrientes, Argentina</LI>';
    print '';
    print '<LI><A target="_blank" href="http://www.coto.com.ar/">COTO C.I.C.S.A. Supermarket</A>, Buenos Aires, Argentina</LI>';
    print '</UL><BR>';
    print 'Point of Sail Store Flow System, credit cards authorization system.<BR>';
    print '<A href="img/memoCase.jpg">See Letter</A>';
    print '';
    print '<P><B>1997: Working for my own</B><BR>';
    print 'Design, analisys, construction, testing, implementation, capacitation, technical assistance.<BR>';
    print 'C, C++, Visual C (Win 32) and Clipper 5.2<BR>';
    print '<SPAN class="c2">Here: <A href="myown.html">a list of clients and projects</A>.</SPAN><BR>';
    print 'See Letters:</P>';
    print '';
    print '<UL>';
    print '<LI><A href="img/memoTacu.jpg">Tacuar&#237; Software</A></LI>';
    print '';
    print '<LI><A href="img/memoTesis.jpg">Tesis Organizaci&#243;n y Sistemas</A></LI>';
    print '';
    print '<LI><A href="img/memoAtna.jpg">A.T.N.A.</A></LI>';
    print '';
    print '<LI><A href="img/memoEagle.jpg">MAGNALIFE - Eagle Star</A></LI>';
    print '';
    print '<LI><A href="img/memoExo.jpg">EXO T.C.</A></LI>';
    print '';
    print '<LI><A href="img/memoFk.jpg">FutureKids</A></LI>';
    print '';
    print '<LI><A href="img/memoIac.jpg">I.A.C.</A></LI>';
    print '';
    print '<LI><A href="img/memoPetro.jpg">Copetro</A></LI>';
    print '';
    print '<LI><A href="img/memoEgon.jpg">Egon Zehnder</A></LI>';
    print '';
    print '<LI><A href="img/memoSuinda.jpg">Suinda</A></LI>';
    print '';
    print '<LI><A href="img/memoInti.jpg">Arq. Intili</A></LI>';
    print '';
    print '<LI><A href="img/memoItochu.jpg">Itochu</A></LI>';
    print '</UL><BR>';
    print '<B>1994 to 1996: Construction</B><BR>';
    print '<A target="_blank" href="http://www.sade.com.ar/">SADE Skanska</A>, ex <A target="_blank" href="http://www.pecom.com.ar/">Perez Companc Holding</A><BR>';
    print 'Institutional Memory: working with Clipper 5.2, C, DOS, Windows 3.x and Novell.<BR>';
    print 'All about constructions, architecture, engineering<BR>';
    print '<A href="img/memoSade.jpg">See Letter</A>';
    print '';
    print '<P><B>1993: Mutual</B><BR>';
    print '<A target="_blank" href="http://www.siemens.com.ar/">SIEMENS Holding</A>, JOSE HERNANDEZ MUTUAL<BR>';
    print 'Clipper Summer 87 and Windows 3.1<BR>';
    print '<A href="img/memoJh.jpg">See Letter</A></P>';
    print '';
    print '<P><B>1992: Nestle</B><BR>';
    print 'IMPEL CENTER, <A target="_blank" href="http://www.nestle.com.ar/">NESTLE ARGENTINA S.A.</A><BR>';
    print 'Programming in Clipper, DBase III Plus!<BR> </P>';
    print '';
    print '<P><B>1990: My first job</B><BR>';
    print 'MACRI HOLDING (SOCMA) - <A target="_blank" href="http://www.iecsa.com.ar">IECSA S.A.</A><BR>';
    print 'Technical Archive Area"s programmer: drafts, designs, technical memories related to construction and engineering.</P>';
    print '';
    libconfig.bottomline();
    print '</BODY>';
    print '</HTML>';

main();
