#!/usr/bin/python
#
#   Aug/2008: Javier Fuchs                                    |\_/|   
#             Phone (+54 2944) 525173                        /     \  
#             http://southfox.servehttp.com                 /_.~ ~,_\ 
#                                                              \@/    
import cgi;
import os;
import sys;
import time;
import cgitb; cgitb.enable();

import libconfig;

def main():
    libconfig.starthtmlhead();
    libconfig.pagecss();
    print '  <META name="DESCRIPTION" content="Javier Fuchs: Books">';
    print '';
    print '  <TITLE>Javier Fuchs: Books</TITLE>';
    print '';
    print '<STYLE type="text/css">';
    print ' span.c2 {font-size: 80%}';
    print ' div.c1 {text-align: center}';
    print '</STYLE>';
    print '</HEAD>';
    print '';
    print '<BODY>';
    print '';
    print '  <DIV class="c1">';
    print '    <H1>Technical Books</H1>';
    print '  </DIV>';
    print '';
    print '  <TABLE>';
    print '    <TR>';
    print '      <TD width="10%"></TD>';
    print '';
    print '      <TD width="90%">';
    print '        <DIV class="c1">';
    print '          <H2>Published by:</H2>';
    print '        </DIV>';
    print '';
    print '        <TABLE>';
    print '          <TR>';
    print '            <TD width="50%"></TD>';
    print '';
    print '            <TD width="50%"></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_AddisonWesley.html">Addison Wesley</A></TD>';
    print '';
    print '            <TD><A href="books/T_Netscape.html">Netscape</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Adobe.html">Adobe</A></TD>';
    print '';
    print '            <TD><A href="books/T_NetworkAssociates.html">Network Associates</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_AdvancedSoftware.html">Advanced Software</A></TD>';
    print '';
    print '            <TD><A href="books/T_NewRiders.html">New Riders</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Amacom.html">Amacom</A></TD>';
    print '';
    print '            <TD><A href="books/T_Nokia.html">Nokia</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Apress.html">Apress</A></TD>';
    print '';
    print '            <TD><A href="books/T_NovaLabs.html">NovaLabs</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_BaseBeans.html">BaseBeans</A></TD>';
    print '';
    print '            <TD><A href="books/T_Oracle.html">Oracle</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_BEA.html">BEA</A></TD>';
    print '';
    print '            <TD><A href="books/T_Orbits.html">Orbits</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Borland.html">Borland</A></TD>';
    print '';
    print '            <TD><A href="books/T_OReilly.html">O"Reilly</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Cisco.html">Cisco</A></TD>';
    print '';
    print '            <TD><A href="books/T_PremierPress.html">Premier Press</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Coriolis.html">Coriolis</A></TD>';
    print '';
    print '            <TD><A href="books/T_PrenticeHall.html">Prentice Hall</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_CRC.html">CRC</A></TD>';
    print '';
    print '            <TD><A href="books/T_ProfessionalMindware.html">Professional Mindware</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_DeveloperShedNetwork.html">Developer Shed Network</A></TD>';
    print '';
    print '            <TD><A href="books/T_QUE.html">QUE</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_GNU.html">GNU</A></TD>';
    print '';
    print '            <TD><A href="books/T_RandomHouse.html">Random House</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_HungryMinds.html">Hungry Minds</A></TD>';
    print '';
    print '            <TD><A href="books/T_RogueWave.html">RogueWave</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_IBM.html">IBM</A></TD>';
    print '';
    print '            <TD><A href="books/T_Sams.html">Sams</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_IDG.html">IDG</A></TD>';
    print '';
    print '            <TD><A href="books/T_Sun.html">Sun</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_JGuru.html">JGuru</A></TD>';
    print '';
    print '            <TD><A href="books/T_Sybex.html">Sybex</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_LinuxJournal.html">Linux Journal</A></TD>';
    print '';
    print '            <TD><A href="books/T_TrainingTools.html">Training Tools</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Macmillan.html">Macmillan</A></TD>';
    print '';
    print '            <TD><A href="books/T_W3C.html">W3C</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Macromedia.html">Macromedia</A></TD>';
    print '';
    print '            <TD><A href="books/T_Waite.html">Waite</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_MagelangInstitute.html">Magelang Institute</A></TD>';
    print '';
    print '            <TD><A href="books/T_WebmasterBase.html">Webmaster Base</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Manning.html">Manning</A></TD>';
    print '';
    print '            <TD><A href="books/T_Wiley.html">Wiley</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_McGrawHill.html">McGrawHill</A></TD>';
    print '';
    print '            <TD><A href="books/T_WorldWatch.html">World Watch</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_MindView.html">MindView</A></TD>';
    print '';
    print '            <TD><A href="books/T_Wrox.html">Wrox</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_M&amp;T.html">M&amp;T</A></TD>';
    print '';
    print '            <TD><A href="books/T_ZDU.html">ZDU</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><BR></TD>';
    print '';
    print '            <TD><BR></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/T_Others.html">Others</A></TD>';
    print '';
    print '            <TD></TD>';
    print '          </TR>';
    print '        </TABLE>';
    print '      </TD>';
    print '    </TR>';
    print '  </TABLE>';
    print '  <HR>';
    print '  <!--books/tech.html: END-->';
    print '  <!--books/us/novel.title.html: BEG-->';
    print '';
    print '  <TABLE>';
    print '    <TR>';
    print '      <TD width="10%"></TD>';
    print '';
    print '      <TD width="90%">';
    print '        <DIV class="c1">';
    print '          <H2>Novels, Science Fiction, Biographies</H2>';
    print '        </DIV>';
    print '';
    print '        <H3>Books by Author:</H3><!--books/us/novel.title.html: END-->';
    print '        <!--books/novel.html: BEG-->';
    print '        <!--vim :set nowrap-->';
    print '';
    print '        <TABLE>';
    print '          <TR>';
    print '            <TD><A href="books/N_BovaBen.html">Ben Bova</A></TD>';
    print '';
    print '            <TD><A href="books/N_FreudSigmund.html">Freud, Sigmund</A></TD>';
    print '';
    print '            <TD><A href="books/N_OrwellGeorge.html">Orwell, George</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_BradburyRay.html">Bradbury, Ray</A></TD>';
    print '';
    print '            <TD><A href="books/N_GaldosBenitoPerez.html">Galdos, Benito Perez</A></TD>';
    print '';
    print '            <TD><A href="books/N_Platon.html">Platon</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_BrownDan.html">Brown, Dan</A></TD>';
    print '';
    print '            <TD><A href="books/N_GoetheJohannWolfgang.html">Goethe, Johann Wolfgang</A></TD>';
    print '';
    print '            <TD><A href="books/N_QuinnDaniel.html">Quinn, Daniel</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_BungeCarlos.html">Bunge, Carlos</A></TD>';
    print '';
    print '            <TD><A href="books/N_GolombekDiego.html">Golombek, Diego</A></TD>';
    print '';
    print '            <TD><A href="books/N_RiceAnne.html">Rice, Anne</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_BurroughsWilliam.html">Burroughs, William</A></TD>';
    print '';
    print '            <TD><A href="books/N_HarrisonHarry.html">Harrison, Harry</A></TD>';
    print '';
    print '            <TD><A href="books/N_RowlingJK.html">Rowling, J.K.</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CaparrosMartin.html">Caparros, Martin</A></TD>';
    print '';
    print '            <TD><A href="books/N_HarrisThomas.html">Harris, Thomas</A></TD>';
    print '';
    print '            <TD><A href="books/N_RussellBertrand.html">Russell, Bertrand</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CardOrsonScott.html">Card Orson, Scott</A></TD>';
    print '';
    print '            <TD><A href="books/N_HartzenbuschJuanEugenio.html">Hartzenbusch, Juan Eugenio</A></TD>';
    print '';
    print '            <TD><A href="books/N_SchopenhauerArthur.html">Schopenhauer, Arthur</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CarrollLewis.html">Carroll, Lewis</A></TD>';
    print '';
    print '            <TD><A href="books/N_HawkingStephen.html">Hawking, Stephen</A></TD>';
    print '';
    print '            <TD><A href="books/N_ScottWalterSir.html">Scott, Sir Walter</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CervantesSaavedraMiguelde.html">Cervantes Saavedra, Miguel de</A></TD>';
    print '';
    print '            <TD><A href="books/N_HubbardLRon.html">Hubbard, L. Ron</A></TD>';
    print '';
    print '            <TD><A href="books/N_ShakespeareWilliam.html">Shakespeare, William</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_ChestertonGilbertKeith.html">Chesterton, Gilbert Keith</A></TD>';
    print '';
    print '            <TD><A href="books/N_HuxleyAldous.html">Huxley, Aldous</A></TD>';
    print '';
    print '            <TD><A href="books/N_ShelleyMary.html">Shelley, Mary</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_ChomskyNoam.html">Chomsky, Noam</A></TD>';
    print '';
    print '            <TD><A href="books/N_JimenezJuanRamon.html">Jimenez, Juan Ramon</A></TD>';
    print '';
    print '            <TD><A href="books/N_SmithClarkAshton.html">Smith, Clark Ashton</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_ChristieAgatha.html">Christie, Agatha</A></TD>';
    print '';
    print '            <TD><A href="books/N_KafkaFranz.html">Kafka, Franz</A></TD>';
    print '';
    print '            <TD><A href="books/N_Socrates.html">Socrates</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CiceroMarcusTullius.html">Cicero, Marcus Tullius</A></TD>';
    print '';
    print '            <TD><A href="books/N_KeplerJohannes.html">Kepler, Johannes</A></TD>';
    print '';
    print '            <TD><A href="books/N_Sofocles.html">Sofocles</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_ClancyTom.html">Clancy, Tom</A></TD>';
    print '';
    print '            <TD><A href="books/N_KingLeonard.html">King, Leonard</A></TD>';
    print '';
    print '            <TD><A href="books/N_SteinbeckJohn.html">Steinbeck, John</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CrichtonMichael.html">Crichton, Michael</A></TD>';
    print '';
    print '            <TD><A href="books/N_KingStephen.html">King, Stephen</A></TD>';
    print '';
    print '            <TD><A href="books/N_StephensonNeal.html">Stephenson, Neal</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_CrowleyAleister.html">Crowley, Aleister</A></TD>';
    print '';
    print '            <TD><A href="books/N_KiplingRudyard.html">Kipling, Rudyard</A></TD>';
    print '';
    print '            <TD><A href="books/N_SterlingBruce.html">Sterling, Bruce</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DarwinCharles.html">Darwin, Charles</A></TD>';
    print '';
    print '            <TD><A href="books/N_ClarkeArthurC.html">Clarke, Arthur C.</A></TD>';
    print '';
    print '            <TD><A href="books/N_StokerBram.html">Stoker, Bram</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DefoeDaniel.html">Defoe, Daniel</A></TD>';
    print '';
    print '            <TD><A href="books/N_Krishnamurti.html">Krishnamurti</A></TD>';
    print '';
    print '            <TD><A href="books/N_TolkienJRR.html">Tolkien, J.R.R.</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DescartesRene.html">Descartes, Rene</A></TD>';
    print '';
    print '            <TD><A href="books/N_LearyTimothy.html">Leary, Timothy</A></TD>';
    print '';
    print '            <TD><A href="books/N_TolstoyLeo.html">Tolstoy, Leo</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DickensCharles.html">Dickens, Charles</A></TD>';
    print '';
    print '            <TD><A href="books/N_LinzmayerOwen.html">Linzmayer, Owen</A></TD>';
    print '';
    print '            <TD><A href="books/N_TurtledoveHarry.html">Turtledove, Harry</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DickPhilip.html">Dick, Philip</A></TD>';
    print '';
    print '            <TD><A href="books/N_LordByron.html">Lord Byron</A></TD>';
    print '';
    print '            <TD><A href="books/N_TwainMark.html">Twain, Mark</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DostoyevskyFiodor.html">Dostoyevsky, Fiodor</A></TD>';
    print '';
    print '            <TD><A href="books/N_Machiavello.html">Machiavello</A></TD>';
    print '';
    print '            <TD><A href="books/N_VacaAlvarNunezCabezaDe.html">Vaca, Alvar Nu&#241;ez Cabeza De</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DoyleArthurConan.html">Doyle, Arthur Conan</A></TD>';
    print '';
    print '            <TD><A href="books/N_MarxKarl.html">Marx, Karl</A></TD>';
    print '';
    print '            <TD><A href="books/N_ValleInclanRamonDel.html">Valle Inclan, Ram&#243;n del</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_DungeonsAndDragons.html">Dungeons And Dragons</A></TD>';
    print '';
    print '            <TD><A href="books/N_McCulleyJohnston.html">McCulley, Johnston</A></TD>';
    print '';
    print '            <TD><A href="books/N_VillarinoBasilio.html">Villarino, Basilio</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_EcoUmberto.html">Eco, Umberto</A></TD>';
    print '';
    print '            <TD><A href="books/N_MooreMichael.html">Moore, Michael</A></TD>';
    print '';
    print '            <TD><A href="books/N_Voltaire.html">Voltaire</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_EinsteinAlbert.html">Einstein, Albert</A></TD>';
    print '';
    print '            <TD><A href="books/N_NietzscheFriedrichWilhelm.html">Nietzsche, Friedrich Wilhelm</A></TD>';
    print '';
    print '            <TD><A href="books/N_WellsHG.html">Wells, H.G.</A></TD>';
    print '          </TR>';
    print '        </TABLE><!--books/novel.html: END-->';
    print '        <!--books/us/novel.other.html: BEG-->';
    print '        <HR>';
    print '';
    print '        <P>Other books:</P>';
    print '';
    print '        <TABLE>';
    print '          <TR>';
    print '            <TD><A href="books/N_Che.html">Che</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_Dictionaries.html">Dictionaries</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_Macmillan.html">Macmillan</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_MartialArts.html">Martial Arts</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_MIT.html">MIT</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_PopularScience.html">Popular Science</A></TD>';
    print '          </TR>';
    print '';
    print '          <TR>';
    print '            <TD><A href="books/N_Science.html">Science</A></TD>';
    print '          </TR>';
    print '        </TABLE>';
    print '      </TD>';
    print '    </TR>';
    print '  </TABLE>';
    print '';
    libconfig.bottomline();
    print '</BODY>';
    print '</HTML>';

main();
