#!/usr/bin/python
#
#   Aug/2008: Javier Fuchs                                    |\_/|   
#             Phone (+54 2944) 525173                        /     \  
#             http://southfox.servehttp.com                 /_.~ ~,_\ 
#                                                              \@/    
import cgi;
import os;
import sys;
import time;
import cgitb; cgitb.enable();

import libconfig;

def main():
    libconfig.starthtmlhead();
    libconfig.pagecss();
    print '<META name="DESCRIPTION" content="Javier Fuchs: C">';
    print '';
    print '<TITLE>Javier Fuchs: C</TITLE>';
    print '';
    print '<STYLE type="text/css">';
    print 'span.c2 {font-size: 80%}';
    print 'div.c1 {text-align: center}';
    print '</STYLE>';
    print '</HEAD>';
    print '';
    print '<BODY>';
    print '<HR>';
    print '';
    print '<DIV class="c1">';
    print '<H1>Javier Fuchs C</H1>';
    print '</DIV>';
    print '';
    print '<H2>Examples</H2>';
    print '';
    print '<UL>';
    print '<LI><A href="cgipy/c.py#tree">Tree-node</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#clisrv">Client - Server: TCP/IP</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#trace">Trace: function with variable-arguments</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#fecha">Validate date and day of the week</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#findchar">Analize string</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#matriz4x5">Matrix 4x5: interchange and sort</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#vector-int">Vector of integers</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#fibonacci">Fibonacci Serie</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#azar">Random numbers</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#heap1">Heap: Memory pointers</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#heap2">Heap2: implementing malloc and free</A></LI>';
    print '';
    print '<LI><A href="cgipy/c.py#burbuja">Sort: Buble Algorithm</A></LI>';
    print '</UL>';
    print '<HR>';
    print '';
    print '<H2><A name="tree" id="tree">Tree-node</A></H2>Build a binary-tree and traverse it:';
    print '';
    print '<UL>';
    print '<LI>preorder</LI>';
    print '';
    print '<LI>inorder</LI>';
    print '';
    print '<LI>posorder</LI>';
    print '</UL>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source Code TreeNode.c" href="c/TreeNode.c.html">TreeNode.c</A></TD>';
    print '';
    print '  <TD>Implementation</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="clisrv" id="clisrv">Client - Server: TCP/IP</A></H2>Implementation of two programs: a client and a server.';
    print '';
    print '<P>The client connects to the server.</P>';
    print '';
    print '<P>The Server waits the connection of clientes:</P>';
    print '';
    print '<UL>';
    print '<LI>When a client ask the server with a number, the server creates a child process (<B>fork</B>), and follows it.</LI>';
    print '';
    print '<LI>When the server receives &lt;number&gt;&lt;timeout&gt;, it controls the child process, asking the state of the child process. Using shared memory (<B>mmap</B>)</LI>';
    print '</UL>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Server" href="c/clisrv.srv.c.html">srv.c</A><BR></TD>';
    print '';
    print '  <TD>Server</TD>';
    print '</TR>';
    print '';
    print '<TR>';
    print '  <TD width="20%"><A title="Client" href="c/clisrv.cli.c.html">cli.c</A><BR></TD>';
    print '';
    print '  <TD>Client</TD>';
    print '</TR>';
    print '';
    print '<TR>';
    print '  <TD width="20%"><A title="errores.c" href="c/clisrv.errores.c.html">errores.c</A><BR></TD>';
    print '';
    print '  <TD>Error handling: from book Advanced Programming in the Unix Environment, Stevens)</TD>';
    print '</TR>';
    print '';
    print '<TR>';
    print '  <TD width="20%"><A title="errores.h" href="c/clisrv.errores.h.html">errores.h</A><BR></TD>';
    print '';
    print '  <TD>Error handling: from book Advanced Programming in the Unix Environment, Stevens)</TD>';
    print '</TR>';
    print '';
    print '<TR>';
    print '  <TD width="20%"><A title="ourhdr.h" href="c/clisrv.ourhdr.h.html">ourhdr.h</A><BR></TD>';
    print '';
    print '  <TD>Header: from book Advanced Programming in the Unix Environment, Stevens)</TD>';
    print '</TR>';
    print '';
    print '<TR>';
    print '  <TD width="20%"><A title="Makefile" href="c/clisrv.makefile.html">makefile</A><BR></TD>';
    print '';
    print '  <TD>makefile</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="trace" id="trace">Trace: function with variable-arguments</A></H2>Saves in a file the argument variables following the specified format-printf';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code trace.c" href="c/trace.c.html">trace.c</A></TD>';
    print '';
    print '  <TD>trace and test functions</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="fecha" id="fecha">Validate date and day of the week</A></H2>Ask for a date (day, month, year), between 1950 and 2060, and tells you the day of the week.';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code fecha.c" href="c/fecha.c.html">fecha.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="findchar" id="findchar">Analize string</A></H2>This function receives a string and a character, and returns how many words of the string begins with this character.';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code findchar.c" href="c/findchar.c.html">findchar.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="matriz4x5" id="matriz4x5">Matrix 4x5: interchange and sort</A></H2>This function receives a matrix (4x5), interchange the first and the third row and sort the first row descendent.';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code matriz4x5.c" href="c/matriz4x5.c.html">matriz4x5.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="vector-int" id="vector-int">Vector of integers</A></H2>This function receives a vector of integers, one positive, and the other negative. The function ends with 0.';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code" href="c/vectorint.c.html">vectorint.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="fibonacci" id="fibonacci">Fibonacci Serie</A></H2>The program ask for a natural-number between 0 and 50. Then prints the Fibonacci Serie until the last number of order.';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code" href="c/fibonacci.c.html">fibonacci.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="azar" id="azar">Random numbers</A></H2>';
    print '';
    print '<P>This program lets you play. Generates a number randomly (integer, between 1 and 10). You have to try to guess the number and the program tells you if the number is greather or minus.</P>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code" href="c/azar.c.html">azar.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="heap1" id="heap1">Heap: Memory pointers</A></H2>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code" href="c/heap1.c.html">heap1.c</A></TD>';
    print '';
    print '  <TD>Programa.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '<A name="tip" id="tip"></A>';
    print '';
    print '<H2><A name="heap2" id="heap2">Heap2: implementing malloc and free</A></H2>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code" href="c/heap2.c.html">heap2.c</A></TD>';
    print '';
    print '  <TD>Program.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    print '<H2><A name="burbuja" id="burbuja">Sort: Buble Algorithm</A></H2>';
    print '';
    print '<P>Source code:</P>';
    print '';
    print '<TABLE border="1" cellspacing="0" cellpadding="1">';
    print '<TR>';
    print '  <TD width="20%"><A title="Source code burbuja.c" href="c/burbuja.c.html">burbuja.c</A></TD>';
    print '';
    print '  <TD>Test.</TD>';
    print '</TR>';
    print '</TABLE>';
    print '<HR>';
    print '';
    libconfig.bottomline();
    print '</BODY>';
    print '</HTML>';

main();
