#!/usr/bin/python
#
#   Aug/2008: Javier Fuchs                                    |\_/|   
#             Phone (+54 2944) 525173                        /     \  
#             http://southfox.servehttp.com                 /_.~ ~,_\ 
#                                                              \@/    
import cgi;
import os;
import sys;
import time;
import cgitb; cgitb.enable();

import libconfig;

def main():
    libconfig.starthtmlhead();
    libconfig.pagecss();

    print '  <META name="DESCRIPTION" content="Javier Fuchs - Bio: Working for my own">';
    print '';
    print '  <TITLE>Javier Fuchs - Bio: Working for my own</TITLE>';
    print '';
    print '';
    print '<STYLE type="text/css">';
    print ' span.c2 {font-size: 80%}';
    print ' div.c1 {text-align: center}';
    print '</STYLE>';
    print '</HEAD>';
    print '';
    print '';
    print '';
    print '<BODY>';
    print '';
    print '';
    print '';
    print '  <DIV class="c1">';
    print '    <H1>Outsourcing</H1>';
    print '';
    print '    <H2>For my own.</H2>';
    print '  </DIV>';
    print '';
    print '  <TABLE border="1" cellspacing="0" cellpadding="0">';
    print '    <TR>';
    print '      <TD><B>Technical Aspects</B></TD>';
    print '';
    print '      <TD><B>Project</B></TD>';
    print '';
    print '      <TD><B>Enterprise</B></TD>';
    print '';
    print '      <TD width="7%"><B>Period</B></TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: C/C++<BR>';
    print '      (Visual C++ 6.0)<BR>';
    print '      OS: Linux / Windows';
    print '  </TD>';
    print '';
    print '      <TD>Product WordFix (repair software for the recovery of corrupt documents, including those caused by a virus). OLE Compound Files (MSWord Format).</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.cimaware.com/">Cimaware SL</A>';
    print '          <BR>Telecommute from Bariloche to Spain</TD>';
    print '';
    print '      <TD>4 months (Dec/07)</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '        <TD>Lang: Python, C/C++, UNIX Shell Script <BR>';
    print '            OS: Debian - DB: MySQL.  <BR>';
    print '            Tools: trac, svn, exim';
    print '        </TD>';
    print '        <TD>';
    print '            Project: Antispam technologies (most of which are written in Python) involving some stuffs like exim, clamav, openssl, wxPython, ZODB.';
    print '        </TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.spamexperts.com">SpamExperts</A>';
    print '          <BR>Telecommute from Bariloche to The Netherlands</TD>';
    print '';
    print '      <TD>2 months (Mar/07)</TD>';
    print '    </TR>';
    print '';
    print '    <TR><br>';
    print '      <TD>Lang: Java, JSP, Struts<BR>';
    print '      DB: PostgreSQL<BR>';
    print '      OS: RedHat 9<BR></TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.jus.gov.ar/minjus/ssjyal/IGJ/Inicial.htm">General Department of Justice</A>: Oracle Forms to Java migration.</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.bancomundial.org.ar/">World Bank</A> (<A target="_blank" href="http://www.jus.gov.ar">Ministery of Justice and Human Rights</A>) ';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>4 months (Mar/04)</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: C - Assembler<BR>';
    print '      OS: Windows<BR>';
    print '      Tools: CrossCode C Compiler for 68xxx<BR></TD>';
    print '';
    print '      <TD>Software Maintenance and Analisys of Multikit (Motorola DragonBall Microprocessor)</TD>';
    print '';
    print '      <TD>Neat Latin (<A target="_blank" href="http://www.pre-pago.com/">Pre-pago</A>)<BR>';
    print '      BsAs (Argentina)<BR></TD>';
    print '';
    print '      <TD>2 months (Jan/04)</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Languages: Visual C/C++, Win32API, WMI - GNU C/C++<BR>';
    print '      OS: Windows NT, 2000, XP - Linux RH 9</TD>';
    print '';
    print '      <TD>Several routines for encryption, hardware information (microprocessor, MAC, etc),</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.softoffice.com.ar/">Soft Office</A><BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>1 month<BR>';
    print '      Dic/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang.: C, C++, Shell Scripts<BR>';
    print '      DB: Oracle 7.3<BR>';
    print '      OS: Solaris 7/8, Tru64, VMS</TD>';
    print '';
    print '      <TD>Base Software" Libraries by Solaris 7 to 8 Migration</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.movi.com.ar/">Bell South - Movicom</A><BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>1 month<BR>';
    print '      Oct/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Language: C, HTML, Fox, Shell Scripts<BR>';
    print '      DB: MySQL<BR>';
    print '      OS: Linux, SCO</TD>';
    print '';
    print '      <TD>';
    print '        Programming and maintaining several systems:';
    print '';
    print '        <UL>';
    print '          <LI>Licitations: sending by mails</LI>';
    print '';
    print '          <LI>Partners.</LI>';
    print '';
    print '          <LI>Accounting.</LI>';
    print '        </UL>Administering 2 servers (Linux and SCO), maintaining a web-page and attending users.';
    print '      </TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.uape.org.ar/">Uni&#243;n Argentina de Proveedores del Estado (UAPE)</A><BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>1 month<BR>';
    print '      Jul/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Servlets (Struts), JSP, Java, JDBC.<BR>';
    print '      DB: DB2, Oracle. OS: Linux<BR>';
    print '      Web Server: Websphere, JBoss.<BR>';
    print '      Tools: IntelliJ Idea, ant, jikes, javamake.</TD>';
    print '';
    print '      <TD>Tourism related software.</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.turix.com.ar/">Turix</A><BR>';
    print '      Client: Intertur<BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>2 weeks<BR>';
    print '      Jun/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: C using Guardian APIs.<BR>';
    print '      OS: Tandem</TD>';
    print '';
    print '      <TD>ATM related</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.artsysc.com/">ART System</A><BR>';
    print '      Client: <A target="_blank" href="http://www.redlink.com.ar">Red Link</A><BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>1 month<BR>';
    print '      May/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Java Sitraka (JClass) - J2EE: EJBs (Entity Beans: BMP, CMP. Session Beans).<BR>';
    print '      DB: Oracle 9, OS: Windows<BR>';
    print '      Tools: JBuilder 7, Toad, SQL-Navigator<BR>';
    print '      App.Server: JBoss</TD>';
    print '';
    print '      <TD>VB to Java Migration of Ingenio: Solution to the Industrial Relations area Software (Human Resources management).</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.microstar.com.ar/">Microstar</A><BR>';
    print '      Client: <A target="_blank" href="http://www.cadisa.com/">CADISA</A><BR>';
    print '      BsAs (Argentina)</TD>';
    print '';
    print '      <TD>1 month<BR>';
    print '      Apr/03</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: PL/SQL, Shell script<BR>';
    print '      DB: Oracle 8, OS: Solaris<BR>';
    print '      Tools: Toad, SQLPLUS, Reflexion, Enterprise Manager, Schema Manager, Procedure Builder</TD>';
    print '';
    print '      <TD>DB2 - Oracle Migration.<BR>';
    print '      Packages and Procedures.</TD>';
    print '';
    print '      <TD>Top Service<BR>';
    print '      Clients: <A target="_blank" href="http://www.oracle.com.ar">Oracle</A>, <A target="_blank" href="http://www.impsat.com.ar">IMPSAT</A>, <A target="_blank" href=';
    print '      "http://www.rentas.mendoza.gov.ar/">D.G.R. Mendoza</A></TD>';
    print '';
    print '      <TD>2 weeks</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Visual C++ 6.0, VB6.0, PL/SQL, Transact SQL - DB: Oracle 7.3 - SQL Server 6.5/7.0 - OS: Win NT<BR>';
    print '      Tools: Project 97 - Forms 4.5 - Enterprise Manager - MS-ISQL/w - SQLPLUS</TD>';
    print '';
    print '      <TD>Automated Collection Machine-Collateral. ODBC, DAO, NT Services, DLLs for VB and Forms 4.5: Read/Write COM Ports (OMRON IC Card), Wrappers, File Properties</TD>';
    print '';
    print '      <TD><A target="_blank" href="http://www.nixor.com.ar">NIXOR S.R.L.</A><BR>';
    print '      Client: Citibank N.A.<BR></TD>';
    print '';
    print '      <TD>2 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: C, Pro*C, PL/SQL, UNIX Shell Scripts<BR>';
    print '      DB: Oracle 7.3<BR>';
    print '      OS: HP UX DOS - Win NT</TD>';
    print '';
    print '      <TD>Project: Pre-facturation System.<BR>';
    print '      Validation and Valorization of the phones calls (Telex, Voice, Data).</TD>';
    print '';
    print '      <TD>TESIS Organizaci&#243;n y Sistemas S.A.<BR>';
    print '      Client: TYSSA S.A. (TELEFONICA de ARGENTINA Holding)<BR>';
    print '      <A href="img/memoTesis.jpg">See letter</A></TD>';
    print '';
    print '      <TD>5 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: C/C++, Clipper 5.2, VBA<BR>';
    print '      Tools: MSOffice 95, MS-Visual C 5.0<BR>';
    print '      DB: DBF, Fox - OS: DOS 6.22, Win 95</TD>';
    print '';
    print '      <TD>Design, analysis, implementation of information systems.<BR>';
    print '      Mailing System. VBA (Excel)</TD>';
    print '';
    print '      <TD>Organizaci&#243;n SUINDA S.R.L.<BR>';
    print '      <A href="img/memoSuinda.jpg">See letter</A></TD>';
    print '';
    print '      <TD>3 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: VBA<BR>';
    print '      Tools: MSOffice 97 (Word, Excel, Powerpoint, Access), internet browsers, Mail, FTP<BR>';
    print '      DB: Access - OS: Win 95/98</TD>';
    print '';
    print '      <TD>Informatic Instructor in Operative system, office, Internet. VBA programming (Access - Excel), Macros.</TD>';
    print '';
    print '      <TD>EXO S.A.<BR>';
    print '      Clients: HENRY MARTIN LISDERO &amp; ASOC. INLAND - VIDRIERIA ARGENTINA S.A. (VASA) - VOLKSWAGEN ARGENTINA S.A. - U.B.M.<BR>';
    print '      BsAs, Lavall&#243;l, General Pacheco (Argentina)<BR>';
    print '      <A href="img/memoExo.jpg">See letter</A></TD>';
    print '';
    print '      <TD>2 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: VBA<BR>';
    print '      Tools: MSOffice 95 (Word, Excel, Powerpoint)<BR>';
    print '      OS: Win 95</TD>';
    print '';
    print '      <TD>Project: MAC to PC migration<BR>';
    print '      Instruction in OSs, office.<BR>';
    print '      Macros: VBA with Excel 95 (Number to letter conversion)</TD>';
    print '';
    print '      <TD>INVISA Argentina<BR>';
    print '      Client: EGON ZEHNDER INTERNATIONAL S.A.<BR>';
    print '      Bs.As. (Argentina)<BR>';
    print '      <A href="img/memoEgon.jpg">See letter</A></TD>';
    print '';
    print '      <TD>2 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Tools: MSOffice 97 (Word, Excel, Powerpoint), MSWorks, Corel 6, Autocad, Internet. - OS: Win 95/98</TD>';
    print '';
    print '      <TD>Instruction in OSs, office, graphics design and Internet.</TD>';
    print '';
    print '      <TD>FutureKids<BR>';
    print '      Caballito, Bs.As. (Arg.)<BR>';
    print '      <A href="img/memoFk.jpg">See letter</A></TD>';
    print '';
    print '      <TD>5 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Tools: MSOffice 95 (Word, Excel, Powerpoint) - OS: Win 95</TD>';
    print '';
    print '      <TD>Instruction in OSs, office.</TD>';
    print '';
    print '      <TD>ITOCHU Argentina S.A.<BR>';
    print '      <A href="img/memoItochu.jpg">See letter</A></TD>';
    print '';
    print '      <TD>1 month</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: VBA<BR>';
    print '      Tools: MSOffice 95 (Word, Excel, Powerpoint, Access) - MS-Project 4.0<BR>';
    print '      DB: Access - OS: Win 95</TD>';
    print '';
    print '      <TD>Instruction in OSs, office.<BR>';
    print '      Macros: VBA with Excel 95.</TD>';
    print '';
    print '      <TD>ORANGE T.C. S.R.L.<BR>';
    print '      Clients: CITIBANK N.A. - EMPRESSE PROP. - EUROLUBE S.A. (AGIP PETROLI FIAT SEVEL ARGENTINA) - YPF S.A.<BR>';
    print '      Bs.As., Tigre (Arg.)</TD>';
    print '';
    print '      <TD>4 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: VBA<BR>';
    print '      Tools: MSOffice 95, 97 (Word, Excel, Powerpoint, Access), Corel 6<BR>';
    print '      DB: Access - OS: Win 95/98</TD>';
    print '';
    print '      <TD>Instruction in OSs, office, graphics design and Internet.</TD>';
    print '';
    print '      <TD>D.O.Q. Consultora<BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>6 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: VBA<BR>';
    print '      Tools: Win 3.11, MS-Access<BR>';
    print '      DB: Access - OS: DOS</TD>';
    print '';
    print '      <TD>MS-Access Development</TD>';
    print '';
    print '      <TD>I.A.C. (Instituto Argentino de Computaci&#243;n)<BR>';
    print '      Bs.As.<BR>';
    print '      <A href="img/memoIac.jpg">See letter</A></TD>';
    print '';
    print '      <TD>3 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Tools: MS-Word, MS-Excel<BR>';
    print '      OS: Win 95</TD>';
    print '';
    print '      <TD>Instruction in OSs, office.</TD>';
    print '';
    print '      <TD>Copetro S.A. <BR>';
    print '      <A href="img/memoPetro.jpg">See letter</A></TD>';
    print '';
    print '      <TD>1 month</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Tools: MSOffice 95 (Word, Excel, Powerpoint)<BR>';
    print '      OS: DOS 6.22, Win 95</TD>';
    print '';
    print '      <TD>Instruction in OSs, office.</TD>';
    print '';
    print '      <TD>MAGNALIFE S.A. (EAGLE STAR Agent)<BR>';
    print '      <A href="img/memoEagle.jpg">See letter</A></TD>';
    print '';
    print '      <TD>1 year</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Visual C 5.0, VBA - Tools: MSOffice 95 (Word, Excel, Ppoint, Access)<BR>';
    print '      DB: Access - OS: DOS 6.22, Win 95</TD>';
    print '';
    print '      <TD>Instruction in OSs, office and programming. Macros: VBA (Excel and Access)<BR>';
    print '      Programming: Visual C 5.0</TD>';
    print '';
    print '      <TD>Centro de Actividades Inform&#225;ticas S.A. (CAI)<BR>';
    print '      Bs.As. (Argentina)</TD>';
    print '';
    print '      <TD>17 months</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Tools: MSOffice 95 (Word, Excel), Perfect Works, Internet and Modem<BR>';
    print '      OS: Win 95</TD>';
    print '';
    print '      <TD>Technical assistance, Hardware and Software installation, and general instruction.</TD>';
    print '';
    print '      <TD>Asociaci&#243;n de Astilleros y Talleres Navales Argentinos (A.T.N.A.)<BR>';
    print '      <A href="img/memoAtna.jpg">See letter</A></TD>';
    print '';
    print '      <TD>2 years</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Clipper 5.2, Visual C 5.0<BR>';
    print '      Tools: MSOffice 95/97, Corel 6 (Draw, Photo Paint), Autocad 12 (2D-3D) and Autocad Ligth<BR>';
    print '      DB: Access, DBF<BR>';
    print '      OS: DOS 6.22, Win 95/98</TD>';
    print '';
    print '      <TD>Instruction in 2D-3D with Autocad, Office and OSes.<BR>';
    print '      Programming, analysis, development and implementation: Technical Organization for Construction Projects. Compute Budget System.</TD>';
    print '';
    print '      <TD>Jos&#233; Juan Intili Architect<BR>';
    print '      Bs.As. (Argentina)<BR>';
    print '      <A href="img/memoInti.jpg">See letter</A></TD>';
    print '';
    print '      <TD>2 years</TD>';
    print '    </TR>';
    print '';
    print '    <TR>';
    print '      <TD>Lang: Visual C 5.0 VB - VBA<BR>';
    print '      Tools: MSOFFICE 95 (Word, Excel, Powerpoint, Access), Autocad 12, Autocad Ligth, Corel 6<BR>';
    print '      DB: Access - DBF (Fox)<BR>';
    print '      OS: DOS 6.22 - Win 95</TD>';
    print '';
    print '      <TD>Training:<BR>';
    print '      * Junior &amp; Master PC Operator.<BR>';
    print '      * C &amp; Access programming.<BR>';
    print '      * Executive Secretary.<BR>';
    print '      Programming at: Sales Statistics System (Villard &amp; Louis)</TD>';
    print '';
    print '      <TD>Centro EXCED S.R.L.<BR>';
    print '      Clients: A.G.A. - Bus 132 - INTER*CONTINENTAL Hotel - QUILMES - VILLARD &amp; LOUIS S.A.<BR>';
    print '      Buenos Aires, San Mart&#237;n, Munro (Arg.)</TD>';
    print '';
    print '      <TD>1 year</TD>';
    print '    </TR>';
    print '  </TABLE>';
    print '';
    print '  <P></P>';
    print '';
    libconfig.bottomline();
    print '</BODY>';
    print '</HTML>';

main();
