#!/usr/bin/python
#
#   Aug/2008: Javier Fuchs                                    |\_/|   
#             Phone (+54 2944) 525173                        /     \  
#             http://southfox.servehttp.com                 /_.~ ~,_\ 
#                                                              \@/    
import cgi;
import os;
import sys;
import time;
import cgitb; cgitb.enable();

import libconfig;

def main():
    libconfig.starthtmlhead('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN http://www.w3.org/TR/html4/loose.dtd">');
    libconfig.pagecss();
    print '  <META name="DESCRIPTION" content="Javier Fuchs: oracle">';
    print '';
    print '  <TITLE>Javier Fuchs: oracle</TITLE><!--oracle/us/head.title.html: END-->';
    print '';
    print '<STYLE type="text/css">';
    print ' span.c2 {font-size: 80%}';
    print ' div.c1 {text-align: center}';
    print '</STYLE>';
    print '</HEAD>';
    print '';
    print '<BODY>';
    print '';
    print '  <DIV>';
    print '    <TABLE cellspacing="0" cellpadding="0" width="100%">';
    print '      <TR>';
    print '        <TD valign="bottom" width="33%">';
    print '          <TABLE cellspacing="0" cellpadding="0">';
    print '            <TR>';
    print '              <TD align="center"><A href="oracle/que-es.html"><IMG src="img/rarrow.gif" alt="Next" border="0" height="30" width="30"></A></TD>';
    print '            </TR>';
    print '          </TABLE>';
    print '        </TD>';
    print '';
    print '        <TD></TD>';
    print '';
    print '        <TD valign="bottom" align="right" width="33%"></TD>';
    print '      </TR>';
    print '    </TABLE><IMG src="img/line.gif" width="100%" height="1">';
    print '  </DIV>';
    print '';
    print '  <DIV class="c1">';
    print '    <H1>Oracle</H1>';
    print '  </DIV>';
    print '';
    print '  <UL>';
    print '    <LI><A href="oracle/que-es.html">What is Oracle?</A></LI>';
    print '';
    print '    <LI><A href="oracle/server.html">Oracle Server</A></LI>';
    print '';
    print '    <LI><A href="oracle/sql-plus.html">SQL*Plus (friendly interface :)</A></LI>';
    print '';
    print '    <LI><A href="oracle/forms.html">Oracle Forms</A></LI>';
    print '';
    print '    <LI><A href="oracle/reports.html">Oracle Reports</A></LI>';
    print '';
    print '    <LI><A href="oracle/loaderconnect.html">Oracle Loader &amp; SQL*Connect</A></LI>';
    print '';
    print '    <LI><A href="oracle/developer.html">Developer 2000 &amp; Designer 2000</A></LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/arq.html">ARCHITECTURE</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/arq.html#term">Terminology</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#bd">What is a database?</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#tablespace">tablespace</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#rollback">Rollback register</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#ctrl">Control Files</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#progs">Programs</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#soporte">Support process of the database</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#memoria">Memory Structure</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#instancia">What is an Oracle instance?</A></LI>';
    print '';
    print '        <LI><A href="oracle/arq.html#todo">All in one</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/objetos.html">Database Objects</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/objetos.html#tabla">Tables</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#vista">Views</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#indice">Indexes</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#sino">Synonyms</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#grant">Grants</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#rol">Groups and Functions</A></LI>';
    print '';
    print '        <LI><A href="oracle/objetos.html#dict">Data Dictionary</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/sql.html">SQL</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/sql.html#dostipos">Two types of SQL-Sentences</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#plus">SQL*Plus</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#createtable">CREATE TABLE sentency</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#tiposdatos">Datatypes</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#describe">DESCRIBE</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#altertable">ALTER TABLE</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#createindex">CREATE INDEX</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#select">SELECT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#union">UNION</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#intersect">INTERSECT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#minus">MINUS</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#insert">INSERT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#delete">DELETE</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#update">UPDATE</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#opercompar">Most used Compare operations</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#fncnum">Functions for Numbers</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#fncchar">Functions for datatype CHAR</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#fncdate">DATE Functions</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#timezones">Valid time zones</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#fncmiscel">Miscelaneuos Functions</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#fncgrupo">Group Functions</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#funcconvertipo">Type conversions functions</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#formatodate">DATE formats</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#formatocharnum">TO_CHAR and TO_NUMBER formats</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#commit">COMMIT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#rollback">ROLLBACK</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#savepoint">SAVEPOINT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#connect">CONNECT</A></LI>';
    print '';
    print '        <LI><A href="oracle/sql.html#disconnect">DISCONNECT</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/plsql.html">PL/SQL</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/plsql.html#aritm">Arithmetics operations</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#relac">Logic Operations</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#simbol">Other symbols</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#compon">Components of PL/SQL</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#excep">Excepcions</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#cursor">Cursors</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#control">Control Structures</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#block">Block Structure</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#bucle">Infinite Structures</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#procedure">Procedures</A></LI>';
    print '';
    print '        <LI><A href="oracle/plsql.html#function">Functions</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI><A href="oracle/packages.html">Packages</A></LI>';
    print '';
    print '    <LI><A href="oracle/triggers.html">Database Triggers</A></LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/objtype.html">Objects Type</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/objtype.html#createtype">Create Type</A></LI>';
    print '';
    print '        <LI><A href="oracle/objtype.html#createtypebody">Objects Type Body</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/ajuste.html">Tuning of aplications</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/ajuste.html#termino">Terminology</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#optimiza">Optimization</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#enfoque">How to do it?</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#tuning">Tuning</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#ejecucion">Ejecution</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#obtencion">Obtain</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#asigna">Asigning names to variables</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#queindex">What index?</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#exclinex">Exclusive indexes</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#tools">Tools for tuning process</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#explain">Explain plan</A></LI>';
    print '';
    print '        <LI><A href="oracle/ajuste.html#trace">SQL Trace and tkprof</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/dba.html">DBA</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/dba.html#sqldba">SQLDBA in command line</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/expimp.html">Export - Import</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/expimp.html#exportsinpar">Interactive Export</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#importsinpar">Interactive Import</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#exportconpar">Export with parameters</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#importconpar">Import with parameters</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#modos">Export and import modes</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#requisitos">Requirements for execution of Export and Import</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#error">Error Conditions and solutions</A></LI>';
    print '';
    print '        <LI><A href="oracle/expimp.html#unix">Unix specific questions</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI>';
    print '      <A href="oracle/loader.html">Oracle Loader</A>';
    print '';
    print '      <UL>';
    print '        <LI><A href="oracle/loader.html#exec">Ejecution</A></LI>';
    print '';
    print '        <LI><A href="oracle/loader.html#opc">Options</A></LI>';
    print '';
    print '        <LI><A href="oracle/loader.html#ctl">Control File</A></LI>';
    print '      </UL>';
    print '    </LI>';
    print '';
    print '    <LI><A href="oracle/tip.html">Tips</A></LI>';
    print '';
    print '    <LI><A href="oracle/listacomm.html">Comands</A></LI>';
    print '  </UL>';
    print '';
    print '  <DIV>';
    print '    <IMG src="img/line.gif" width="100%" height="1">';
    print '';
    print '    <TABLE cellspacing="0" cellpadding="0" width="100%">';
    print '      <TR>';
    print '        <TD valign="bottom" width="33%">';
    print '          <TABLE cellspacing="0" cellpadding="0">';
    print '            <TR>';
    print '              <TD align="center"><A href="oracle/que-es.html"><IMG src="img/rarrow.gif" alt="Next" border="0" height="30" width="30"></A></TD>';
    print '            </TR>';
    print '          </TABLE>';
    print '        </TD>';
    print '';
    print '        <TD align="center" width="34%"></TD>';
    print '';
    print '        <TD valign="bottom" align="right" width="33%"></TD>';
    print '      </TR>';
    print '    </TABLE>';
    print '  </DIV><!--oracle/us/body.html: END-->';
    libconfig.bottomline();
    print '</BODY>';
    print '</HTML>';

main();
